apiVersion: v1
kind: Service
metadata:
  labels:
    app: techtrends
    tag: {{ .Values.image.tag }}
    namespace: {{ .Values.namespace.name }}
  name: techtrends
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
  - name: http
    port: {{ .Values.service.port }}
    protocol: {{ .Values.service.protocol }}
    targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}
