apiVersion: v1
kind: Service
metadata:
  annotations: {}
  name: techtrends-server-nodeport
  namespace: sandbox
spec:
  ports:
  - name: http
    port: 4111
    protocol: TCP
    targetPort: 3111
    nodePort: 31234
  selector:
    app: techtrends
  sessionAffinity: None
  type: NodePort

